#include <stdint.h>
#include <stdlib.h>
#include <math.h>
#include <cstdint>
#include <string>
#include <vector>
#include <ssw_cpp20.hpp>
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include <kseq.h>
#include <stdint.h>
#include <string>
#include <vector>
#include <ssw_cpp.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <ssw.h>
